name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # الخطوة 1: التحقق من الكود
      - name: Checkout code
        uses: actions/checkout@v3

      # الخطوة 2: إعداد Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # الخطوة 3: تثبيت التبعيات
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # الخطوة 4: إنشاء ملف تنفيذي باستخدام PyInstaller
      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole "55555555555555 5555555.py"

      # الخطوة 5: رفع الملف التنفيذي إلى قسم الإصدارات
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: captcha-solver
          path: dist/55555555555555 5555555.exe

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: captcha-solver

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/55555555555555 5555555.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
